CREATE TABLE card (
	id INTEGER NOT NULL AUTO_INCREMENT,
	ativo BOOLEAN DEFAULT TRUE,
	nome CHARACTER VARYING(255) NOT NULL,
	segmento CHARACTER VARYING(255) NOT NULL,
	link CHARACTER VARYING(255),
	imagem CHARACTER VARYING(255),
  	PRIMARY KEY (`id`)
);